package com.example.sportlink.ui.screens.create

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.example.sportlink.domain.model.Lobby
import com.example.sportlink.domain.repository.LobbyRepository
import com.example.sportlink.domain.util.Result
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

/**
 * Sealed class representing UI states for Create Lobby Screen.
 */
sealed class CreateLobbyUiState {
    object Idle : CreateLobbyUiState()
    object Loading : CreateLobbyUiState()
    data class Success(val lobby: Lobby) : CreateLobbyUiState()
    data class Error(val message: String) : CreateLobbyUiState()
}

/**
 * ViewModel for Create Lobby Screen.
 * Manages form state and lobby creation.
 * 
 * All dependencies are injected via constructor (10p DI).
 */
@HiltViewModel
class CreateLobbyViewModel @Inject constructor(
    private val lobbyRepository: LobbyRepository
) : ViewModel() {
    
    private val _uiState = MutableStateFlow<CreateLobbyUiState>(CreateLobbyUiState.Idle)
    val uiState: StateFlow<CreateLobbyUiState> = _uiState.asStateFlow()
    
    // Form state
    var sportName by mutableStateOf("")
        private set
    var location by mutableStateOf("")
        private set
    var date by mutableStateOf("")
        private set
    var maxPlayers by mutableStateOf("")
        private set
    var description by mutableStateOf("")
        private set
    
    /**
     * Updates sport name.
     */
    fun updateSportName(value: String) {
        sportName = value
    }
    
    /**
     * Updates location.
     */
    fun updateLocation(value: String) {
        location = value
    }
    
    /**
     * Updates date.
     */
    fun updateDate(value: String) {
        date = value
    }
    
    /**
     * Updates max players.
     */
    fun updateMaxPlayers(value: String) {
        maxPlayers = value
    }
    
    /**
     * Updates description.
     */
    fun updateDescription(value: String) {
        description = value
    }
    
    /**
     * Validates form input.
     */
    private fun validateForm(): String? {
        if (sportName.isBlank()) return "Sport name is required"
        if (location.isBlank()) return "Location is required"
        if (date.isBlank()) return "Date is required"
        val maxPlayersInt = maxPlayers.toIntOrNull()
        if (maxPlayersInt == null || maxPlayersInt <= 0) {
            return "Max players must be a positive number"
        }
        return null
    }
    
    /**
     * Creates a new lobby via POST request.
     */
    fun createLobby() {
        val validationError = validateForm()
        if (validationError != null) {
            _uiState.value = CreateLobbyUiState.Error(validationError)
            return
        }
        
        viewModelScope.launch {
            _uiState.value = CreateLobbyUiState.Loading
            
            val lobby = Lobby(
                id = "", // Will be generated by API
                sportName = sportName,
                location = location,
                date = date,
                maxPlayers = maxPlayers.toInt(),
                joinedPlayers = 0,
                description = description.ifBlank { null }
            )
            
            when (val result = lobbyRepository.createLobby(lobby)) {
                is Result.Success -> {
                    _uiState.value = CreateLobbyUiState.Success(result.data)
                    // Reset form
                    resetForm()
                }
                is Result.Error -> {
                    _uiState.value = CreateLobbyUiState.Error(
                        result.exception.message ?: "Failed to create lobby"
                    )
                }
                else -> {}
            }
        }
    }
    
    /**
     * Resets the form.
     */
    private fun resetForm() {
        sportName = ""
        location = ""
        date = ""
        maxPlayers = ""
        description = ""
    }
}

